apiVersion: v1
kind: Service
metadata:
  name: update
  labels:
    app: update
    service: update
spec:
  ports:
  - port: 8081
    name: grpc
  selector:
    app: update
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: update
  labels:
    app: update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: update
  template:
    metadata:
      labels:
        app: update
    spec:
      containers:
      - name: update
        image: knapsack/update:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        livenessProbe:
          exec:
            command:
            - ./healthz
          initialDelaySeconds: 5
          periodSeconds: 60
