// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: knapsack.proto

package knapsack

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KnapsackDP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	I      int32 `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
	W      int32 `protobuf:"varint,2,opt,name=w,proto3" json:"w,omitempty"`
	Weight int32 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Value  int32 `protobuf:"varint,4,opt,name=value,proto3" json:"value,omitempty"`
	Dp     []*DP `protobuf:"bytes,5,rep,name=dp,proto3" json:"dp,omitempty"`
}

func (x *KnapsackDP) Reset() {
	*x = KnapsackDP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knapsack_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KnapsackDP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnapsackDP) ProtoMessage() {}

func (x *KnapsackDP) ProtoReflect() protoreflect.Message {
	mi := &file_knapsack_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnapsackDP.ProtoReflect.Descriptor instead.
func (*KnapsackDP) Descriptor() ([]byte, []int) {
	return file_knapsack_proto_rawDescGZIP(), []int{0}
}

func (x *KnapsackDP) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *KnapsackDP) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *KnapsackDP) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *KnapsackDP) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *KnapsackDP) GetDp() []*DP {
	if x != nil {
		return x.Dp
	}
	return nil
}

type DP struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row []int32 `protobuf:"varint,1,rep,packed,name=row,proto3" json:"row,omitempty"`
}

func (x *DP) Reset() {
	*x = DP{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knapsack_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DP) ProtoMessage() {}

func (x *DP) ProtoReflect() protoreflect.Message {
	mi := &file_knapsack_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DP.ProtoReflect.Descriptor instead.
func (*DP) Descriptor() ([]byte, []int) {
	return file_knapsack_proto_rawDescGZIP(), []int{1}
}

func (x *DP) GetRow() []int32 {
	if x != nil {
		return x.Row
	}
	return nil
}

type Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *Result) Reset() {
	*x = Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knapsack_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_knapsack_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_knapsack_proto_rawDescGZIP(), []int{2}
}

func (x *Result) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

type Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N      int32   `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	W      int32   `protobuf:"varint,2,opt,name=w,proto3" json:"w,omitempty"`
	Weight []int32 `protobuf:"varint,3,rep,packed,name=weight,proto3" json:"weight,omitempty"`
	Value  []int32 `protobuf:"varint,4,rep,packed,name=value,proto3" json:"value,omitempty"`
}

func (x *Input) Reset() {
	*x = Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_knapsack_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Input) ProtoMessage() {}

func (x *Input) ProtoReflect() protoreflect.Message {
	mi := &file_knapsack_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Input.ProtoReflect.Descriptor instead.
func (*Input) Descriptor() ([]byte, []int) {
	return file_knapsack_proto_rawDescGZIP(), []int{3}
}

func (x *Input) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *Input) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Input) GetWeight() []int32 {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *Input) GetValue() []int32 {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_knapsack_proto protoreflect.FileDescriptor

var file_knapsack_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6b, 0x6e, 0x61, 0x70, 0x73, 0x61, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6b, 0x6e, 0x61, 0x70, 0x73, 0x61, 0x63, 0x6b, 0x22, 0x74, 0x0a, 0x0a, 0x4b, 0x6e,
	0x61, 0x70, 0x73, 0x61, 0x63, 0x6b, 0x44, 0x50, 0x12, 0x0c, 0x0a, 0x01, 0x69, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x01, 0x69, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x01, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1c, 0x0a, 0x02, 0x64, 0x70, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x6b, 0x6e, 0x61, 0x70, 0x73, 0x61, 0x63, 0x6b, 0x2e, 0x44, 0x50, 0x52, 0x02, 0x64, 0x70,
	0x22, 0x16, 0x0a, 0x02, 0x44, 0x50, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x22, 0x20, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x51, 0x0a, 0x05, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01,
	0x6e, 0x12, 0x0c, 0x0a, 0x01, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x77, 0x12,
	0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0x41, 0x0a,
	0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x32, 0x0a, 0x06,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x6b, 0x6e, 0x61, 0x70, 0x73, 0x61, 0x63,
	0x6b, 0x2e, 0x4b, 0x6e, 0x61, 0x70, 0x73, 0x61, 0x63, 0x6b, 0x44, 0x50, 0x1a, 0x10, 0x2e, 0x6b,
	0x6e, 0x61, 0x70, 0x73, 0x61, 0x63, 0x6b, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x68, 0x69, 0x72, 0x75, 0x31, 0x32, 0x32, 0x31, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x6b, 0x6e, 0x61, 0x70, 0x73, 0x61, 0x63, 0x6b, 0x2f, 0x6b,
	0x6e, 0x61, 0x70, 0x73, 0x61, 0x63, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_knapsack_proto_rawDescOnce sync.Once
	file_knapsack_proto_rawDescData = file_knapsack_proto_rawDesc
)

func file_knapsack_proto_rawDescGZIP() []byte {
	file_knapsack_proto_rawDescOnce.Do(func() {
		file_knapsack_proto_rawDescData = protoimpl.X.CompressGZIP(file_knapsack_proto_rawDescData)
	})
	return file_knapsack_proto_rawDescData
}

var file_knapsack_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_knapsack_proto_goTypes = []interface{}{
	(*KnapsackDP)(nil), // 0: knapsack.KnapsackDP
	(*DP)(nil),         // 1: knapsack.DP
	(*Result)(nil),     // 2: knapsack.Result
	(*Input)(nil),      // 3: knapsack.Input
}
var file_knapsack_proto_depIdxs = []int32{
	1, // 0: knapsack.KnapsackDP.dp:type_name -> knapsack.DP
	0, // 1: knapsack.UpdateTable.Update:input_type -> knapsack.KnapsackDP
	2, // 2: knapsack.UpdateTable.Update:output_type -> knapsack.Result
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_knapsack_proto_init() }
func file_knapsack_proto_init() {
	if File_knapsack_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_knapsack_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KnapsackDP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knapsack_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DP); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knapsack_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_knapsack_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_knapsack_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_knapsack_proto_goTypes,
		DependencyIndexes: file_knapsack_proto_depIdxs,
		MessageInfos:      file_knapsack_proto_msgTypes,
	}.Build()
	File_knapsack_proto = out.File
	file_knapsack_proto_rawDesc = nil
	file_knapsack_proto_goTypes = nil
	file_knapsack_proto_depIdxs = nil
}
