// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package knapsack

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UpdateTableClient is the client API for UpdateTable service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateTableClient interface {
	Update(ctx context.Context, in *KnapsackDP, opts ...grpc.CallOption) (*Result, error)
}

type updateTableClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateTableClient(cc grpc.ClientConnInterface) UpdateTableClient {
	return &updateTableClient{cc}
}

func (c *updateTableClient) Update(ctx context.Context, in *KnapsackDP, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/knapsack.UpdateTable/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateTableServer is the server API for UpdateTable service.
// All implementations must embed UnimplementedUpdateTableServer
// for forward compatibility
type UpdateTableServer interface {
	Update(context.Context, *KnapsackDP) (*Result, error)
	mustEmbedUnimplementedUpdateTableServer()
}

// UnimplementedUpdateTableServer must be embedded to have forward compatible implementations.
type UnimplementedUpdateTableServer struct {
}

func (UnimplementedUpdateTableServer) Update(context.Context, *KnapsackDP) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUpdateTableServer) mustEmbedUnimplementedUpdateTableServer() {}

// UnsafeUpdateTableServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateTableServer will
// result in compilation errors.
type UnsafeUpdateTableServer interface {
	mustEmbedUnimplementedUpdateTableServer()
}

func RegisterUpdateTableServer(s grpc.ServiceRegistrar, srv UpdateTableServer) {
	s.RegisterService(&UpdateTable_ServiceDesc, srv)
}

func _UpdateTable_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnapsackDP)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateTableServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/knapsack.UpdateTable/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateTableServer).Update(ctx, req.(*KnapsackDP))
	}
	return interceptor(ctx, in, info, handler)
}

// UpdateTable_ServiceDesc is the grpc.ServiceDesc for UpdateTable service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateTable_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knapsack.UpdateTable",
	HandlerType: (*UpdateTableServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Update",
			Handler:    _UpdateTable_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "knapsack.proto",
}
